/**
 * The deployed worker entry.
 *
 * Exists for one reason: a Durable Object class has to be exported from the
 * worker's own module, and the SvelteKit adapter generates that module, so
 * there is nowhere inside it to add an export. This wraps it.
 *
 * **Do not point `main` at this file.** `@sveltejs/adapter-cloudflare` treats
 * `main` as its *output* path and `rimraf`s it before writing — so
 * `"main": "worker.ts"` makes `npm run build` delete this file. `main` stays on
 * the adapter's default and wrangler takes the entry positionally instead:
 *
 *     wrangler dev worker.ts
 *     wrangler deploy worker.ts
 *
 * which is what `npm run preview:worker` and `npm run deploy` do.
 *
 * It lives at the repo root rather than under `src/` so `svelte-check` does not
 * try to resolve `.svelte-kit/cloudflare/_worker.js` — a build artefact that
 * only exists after a build. The root is outside the `include` list in
 * `.svelte-kit/tsconfig.json`, so this file is bundled by wrangler's esbuild and
 * type-checked by nothing. That makes it, and `durable-object.ts`, a second
 * alias-free zone: esbuild resolves neither `$lib` nor SvelteKit's aliases.
 *
 * Keep it to re-exports. Anything with logic in it is untested by construction.
 */

// @ts-expect-error - generated by `vite build`, so it does not exist until then.
import worker from './.svelte-kit/cloudflare/_worker.js';

export { RealtimeRoom } from './src/lib/server/realtime/durable-object';

export default worker;
