// One schema object for both drizzle-kit and the Better Auth adapter.
//
// `auth.ts` is generated by `npm run auth:schema` and is kept in its own file so
// regenerating it can never clobber the hand-written app tables.
export * from './app';
export * from './auth';
